### ISSUE TITLE
Incorrect component weight for U+23D7B in Plangothic P1:Version 6.399

### ISSUE THREAD

**Issue by JLHwung** [Fitzgerald-Porthmouth-Koenigsegg/Plangothic_Project#29]
<img width="548" alt="image" src="https://github.com/user-attachments/assets/1e192475-09d5-4e76-be2c-dbc39c6d5c3b">

U+23D7B右邊組件「它」字重細了。

Version: Version 6.399;October 10, 2024;FontCreator 14.0.0.2901 64-bit

**Comment by Fitzgerald-Porthmouth-Koenigsegg** [comment]
感谢反馈，下一版本将修复此问题。

**Comment by JLHwung** [comment]
It seems this is a macOS-specific rendering issue:

Rendered in FontBook.app:

<img width="561" alt="d67744a6c61b39ef9538af605c48268a" src="https://github.com/user-attachments/assets/f20ef31e-fee9-4f27-b6a5-19d0521756a0">

<img width="209" alt="a7c05754181b0fd45b136b7874252f08" src="https://github.com/user-attachments/assets/17390a7e-b501-4cdc-b3d0-5e8233f269c5">

Rendered in Pages.app:
<img width="674" alt="a3c29b2e441ee5aa7f1677f3eb13d273" src="https://github.com/user-attachments/assets/7a600cbf-059e-4471-b591-4abc27f11541">

The PDF exported from Pages.app:
[Untitled 2.pages.pdf](https://github.com/user-attachments/files/17588216/Untitled.2.pages.pdf)
